services:

  medilabo_db:
    container_name: medilabo_db
    image: mysql:latest
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: medilabo_db
      MYSQL_ROOT_PASSWORD: HGHJ45JID
    volumes:
            - /volume1/database/msa_data:/var/lib/mysql:rw
    networks:
      - medilaboEnv-network

  note-db:
    container_name: note-db
    image: mongo:latest
    restart: always
    build:
      context: ./mongo
      dockerfile: Dockerfile
    volumes:
            - /volume1/database/note-db:/data/db:rw
    environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - medilaboEnv-network

  medilabo:
    container_name: medilabo
    image: medilabo:latest
    restart: always
    build:
      context: ../medilabo
      dockerfile: Dockerfile
    depends_on:
        - medilabo_db
    networks:
      - medilaboEnv-network
    environment:
      DATASOURCE_URL: jdbc:mysql://medilabo_db:3306/medilabo_db
      DATASOURCE_USERNAME: admin
      DATASOURCE_PASSWORD: password
      LOG_LEVEL: info
    ports:
      - "8081:8081"

  note:
    container_name: note
    image: note:latest
    restart: always
    build:
      context: ../note
      dockerfile: Dockerfile
    depends_on:
      - note-db  
    networks:
      - medilaboEnv-network
    environment:
      MONGO_URI: mongodb://admin:password@note-db:27017/
      MONGO_INITDB_DATABASE: medilabo_database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_AUTO_INDEX_CREATION: true
      LOG_LEVEL: info
    ports:
      - "8082:8082"

  report:
    container_name: report
    image: report:latest
    restart: always
    build:
      context: ../report
      dockerfile: Dockerfile
    depends_on:
      - note
      - medilabo
    networks:
      - medilaboEnv-network
    ports:
      - "8083:8083"

  gateway:
    container_name: gateway
    image: gateway:latest
    restart: always
    build:
      context: ../gateway
      dockerfile: Dockerfile
    depends_on:
      - note
      - medilabo
    networks:
      - medilaboEnv-network
    ports:
      - "8080:8080"

  angular-app:
    container_name: angular-app
    image: angular-app:latest
    restart: always
    build:
      context: ../ui
      dockerfile: Dockerfile
    networks:
      - medilaboEnv-network
    ports:
      - "4200:80"

networks:
  medilaboEnv-network:
      driver: bridge
